// <auto-generated />
namespace interactiveSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RewardIdRewnull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RewardIdRewnull));
        
        string IMigrationMetadata.Id
        {
            get { return "201712060543411_Reward IdRew null"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
