// <auto-generated />
namespace interactiveSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addTypeandOrderinEnterpriseModelandRewardModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTypeandOrderinEnterpriseModelandRewardModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201801240535509_add Type and Order in EnterpriseModel and RewardModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
